DROP DATABASE IF EXISTS supertrunfo;
CREATE DATABASE supertrunfo;
USE supertrunfo;

CREATE TABLE supertrunfo.CARTA (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FORCA INTEGER NOT NULL,
    INTELIGENCIA INTEGER NOT NULL,
    VELOCIDADE INTEGER NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    CONSTRAINT CARTA_pk PRIMARY KEY (ID)
);

-- V2: criação da tabela JOGADOR
CREATE TABLE supertrunfo.JOGADOR (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TOTAL_PARTIDAS INTEGER NOT NULL,
    PERCENTUAL_VITORIAS DOUBLE NOT NULL,
    CONSTRAINT CARTA_pk PRIMARY KEY (ID)
);

-- V3: criação das tabelas PARTIDA e CARTA_PARTIDA
CREATE TABLE supertrunfo.PARTIDA (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    ID_JOGADOR INTEGER NOT NULL,
    ROUNDS_VENCIDOS_JOGADOR INTEGER NOT NULL DEFAULT 0,
    ROUNDS_VENCIDOS_CPU INTEGER NOT NULL DEFAULT 0,
    ROUNDS_EMPATADOS INTEGER NOT NULL DEFAULT 0,
    RESULTADO VARCHAR(255),
    DATA DATE NOT NULL,
    FORCA_UTILIZADA BOOLEAN,
    INTELIGENCIA_UTILIZADA BOOLEAN,
    VELOCIDADE_UTILIZADA BOOLEAN,
    CONSTRAINT PARTIDA_PK PRIMARY KEY (ID),
    CONSTRAINT ID_JOGADOR FOREIGN KEY (ID_JOGADOR)
        REFERENCES supertrunfo.JOGADOR (ID)
);

CREATE TABLE supertrunfo.CARTA_PARTIDA (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    ID_PARTIDA INTEGER NOT NULL,
    ID_CARTA INTEGER NOT NULL,
    DO_JOGADOR BOOLEAN,
    UTILIZADA BOOLEAN,
    CONSTRAINT CARTA_PARTIDA_PK PRIMARY KEY (ID),
    CONSTRAINT ID_PARTIDA FOREIGN KEY (ID_PARTIDA)
        REFERENCES supertrunfo.PARTIDA (ID),
    CONSTRAINT ID_CARTA FOREIGN KEY (ID_CARTA)
        REFERENCES supertrunfo.CARTA (ID)
);